apiVersion: v1
kind: PersistentVolume
metadata:
  name: central-library-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /central-library-data/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: central-library-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---


apiVersion: v1
kind: Pod
metadata:
  name: central-library-pod
  labels:
    app: central-library-pod
spec:
  containers:
  - name: central-library
    image: aleksandarradisic/central-library:latest
    ports:
    - containerPort: 80
    env:
      - name: CENTRAL_LIBRARY_DB_CONNECTION_STRING
        value: "Host=localhost;Database=CentralLibrary;Username=postgres;Password=root"

  - name: central-library-db
    image: postgres
    env:
      - name: POSTGRES_PASSWORD
        value: "root"
      - name: POSTGRES_USER
        value: "postgres"
      - name: POSTGRES_DB
        value: "CentralLibrary"
    ports:
    - containerPort: 5432
    volumeMounts:
    - name: central-library-db-storage
      mountPath: /var/lib/postgresql/data

  volumes:
  - name: central-library-db-storage
    persistentVolumeClaim:
      claimName: central-library-db-pvc