apiVersion: v1
kind: Service
metadata:
  name: central-library-service
spec:
  selector:
    app: central-library-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: central-library-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: central-library-ingress.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: central-library-service
                port:
                  number: 80