apiVersion: v1
kind: PersistentVolume
metadata:
  name: novi-sad-library-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /novi-sad-library-data/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: novi-sad-library-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---




apiVersion: v1
kind: Pod
metadata:
  name: novi-sad-library-pod
  labels:
    app: novi-sad-library-pod
spec:
  containers:
  - name: city-library
    image: aleksandarradisic/city-library:latest
    ports:
    - containerPort: 80
    env:
      - name: CITY_LIBRARY_DB_CONNECTION_STRING
        value: "Host=localhost;Database=CityLibrary;Username=postgres;Password=root"
      - name: CENTRAL_LIBRARY_URL
        value: "$(CENTRAL_LIBRARY_SERVICE_SERVICE_HOST):$(CENTRAL_LIBRARY_SERVICE_SERVICE_PORT)"
      - name: CITY_NAME
        value: Novi Sad

  - name: city-library-db
    image: postgres
    env:
      - name: POSTGRES_PASSWORD
        value: "root"
      - name: POSTGRES_USER
        value: "postgres"
      - name: POSTGRES_DB
        value: "CityLibrary"
    ports:
    - containerPort: 5432
    volumeMounts:
    - name: novi-sad-library-db-storage
      mountPath: /var/lib/postgresql/data

  volumes:
  - name: novi-sad-library-db-storage
    persistentVolumeClaim:
      claimName: novi-sad-library-db-pvc